---
abstract: ~
author: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::MockModule: 0
  Test::MockObject: 0
  Test::Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-CouchDB-Schema
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Getopt::Long: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0.57
  Pod::Usage: 0
  Term::ReadLine: 0
  URI: 0
version: 0.3.05
